# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 744f101e8f075cd1d5c22989a60d6b8434275329b0e84fd454280078c6fc83ee0f5cb560d31603056d46edbc886453599aeed50a39d2961c482fedcac939bb04

test:
  secret_key_base: de6d8ec862b3d92e0f86a94bbe05bf28066124f62bf2a1efed72a69842770f762c17587540524e9bae4baa703c3e653d238550e8f94ff5cb8f7120992a4d4881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
